# Generated by Django 4.2.7 on 2025-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_additional_info_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='medical_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
