# Generated by Django 4.2.7 on 2025-08-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_doctorapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorapplication',
            name='full_name',
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('admin', 'Администратор')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.city'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='diploma',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_applications/diplomas/'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.district'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_applications/licenses/'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='medical_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_applications/photos/'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.region'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20),
        ),
    ]
