# Generated by Django 4.2.7 on 2025-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_doctorapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='doctor_applications/diplomas/'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='doctor_applications/licenses/'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='doctor_applications/photos/'),
        ),
    ]
