# Generated by Django 4.2.7 on 2025-08-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_verify_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='authentication.city'),
        ),
    ]
